name: "deno"
version: "0.2.0-alpha.1"
usage: "Helm charts with Deno"
description: |-
  This plugin allows to use Deno to prepare kubernetes manifests
hooks:
  install: "$HELM_PLUGIN_DIR/scripts/install.sh v1.26.2"
  update: "$HELM_PLUGIN_DIR/scripts/install.sh v1.26.2"
command: "$HELM_PLUGIN_DIR/scripts/run.sh"
