name: "deno"
version: "0.0.2-dev"
usage: "Helm charts with Deno"
description: |-
  This plugin provides Deno for Helm charts
useTunnel: false
hooks:
  install: "$HELM_PLUGIN_DIR/scripts/install.sh 1.4.6"
  update: "$$HELM_PLUGIN_DIR/scripts/install.sh 1.4.6"
command: "$HELM_PLUGIN_DIR/scripts/run.sh"
