name: "deno"
version: "0.1.0-alpha.4"
usage: "Helm charts with Deno"
description: |-
  This plugin provides Deno for Helm charts
useTunnel: false
hooks:
  install: "$HELM_PLUGIN_DIR/scripts/install.sh v1.8.3"
  update: "$HELM_PLUGIN_DIR/scripts/install.sh v1.8.3"
command: "$HELM_PLUGIN_DIR/scripts/run.sh"
