name: Run all tests
on:
  push:

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - uses: denolib/setup-deno@v2
        with:
          deno-version: v1.4.x

      - name: Install helm 3
        run: |
          wget https://get.helm.sh/helm-v3.4.1-linux-amd64.tar.gz -O helm.tar.gz
          tar xvf helm.tar.gz linux-amd64/helm
          echo "$PWD/linux-amd64" >> $GITHUB_PATH

      - name: Install helm-diff
        run: |
          helm plugin install https://github.com/databus23/helm-diff --version v3.1.3

      - name: Install helm-secrets
        run: |
          helm plugin install https://github.com/jkroepke/helm-secrets --version v3.4.1

      - name: Install pugin
        run: make install-plugin

      - name: Start local kubernetes cluster
        uses: engineerd/setup-kind@v0.5.0

      - name: Run tests
        run: make test-all
