name: Run all tests
on:
  push:

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - uses: denolib/setup-deno@v2
        with:
          deno-version: v1.8.x

      - name: Install Age Encryption Tool
        run: |
          wget https://github.com/FiloSottile/age/releases/download/v1.0.0-rc.1/age-v1.0.0-rc.1-linux-amd64.tar.gz -O age.tar.gz
          tar xvf age.tar.gz age/age age/age-keygen
          echo "$PWD/age" >> $GITHUB_PATH

      - name: Install helm-diff
        run: |
          helm plugin install https://github.com/databus23/helm-diff --version v3.1.3

      - name: Install helm-secrets
        run: |
          helm plugin install https://github.com/jkroepke/helm-secrets --version v3.6.1

      - name: Install helm-push
        run: |
          helm plugin install https://github.com/chartmuseum/helm-push --version v0.9.0

      - name: Install plugin
        run: make install-plugin

      - name: Start local kubernetes cluster
        uses: engineerd/setup-kind@v0.5.0

      - name: Run tests
        run: make test-all
