name: Run fast tests
on:
  push:

jobs:
  fast-test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - uses: denolib/setup-deno@v2
        with:
          deno-version: v1.8.x

      - name: Install plugin
        run: make install-plugin

      - name: Run tests
        run: make test
