name: Run fast tests
on:
  push:

jobs:
  fast-test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - uses: denolib/setup-deno@v2
        with:
          deno-version: v1.4.x

      - name: Install helm 3
        run: |
          wget https://get.helm.sh/helm-v3.4.1-linux-amd64.tar.gz -O helm.tar.gz
          tar xvf helm.tar.gz linux-amd64/helm
          echo "$PWD/linux-amd64" >> $GITHUB_PATH

      - name: Install pugin
        run: make install-plugin

      - name: Run tests
        run: make test
